"""Render the monitoring configuration for a machine with no Docker.

`monitoring/` is the source of truth. It is written for the compose stack, so it
addresses its neighbours by service name -- `alertmanager:9093`,
`prometheus:9090`, `host.docker.internal:9108`. On a laptop running the same
three binaries directly those names do not resolve, and the fix people reach for
is a hand-edited second copy of every file.

That copy is the problem this script exists to prevent. The repository grew one:
a `monitoring-scratch` folder holding adapted configs, which drifted from
`monitoring/` the moment either changed -- and it drifted silently, because
nothing compared them. A dashboard fix landed in `monitoring/` and the running
Grafana never saw it, for three hours, with no error anywhere.

So the local variant is generated rather than maintained. Everything that
decides *behaviour* -- scrape intervals, rule files, routing, grouping,
thresholds, panels -- has exactly one definition, in `monitoring/`. The only
thing this script changes is where things live, and the full list of those
changes is ADDRESSES below. `tests/test_monitoring_local.py` asserts that the
rendered output differs from its source on no other line, which is what makes
"only addresses differ" a checkable claim rather than an intention.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MONITORING = REPO / "monitoring"

# The whole of the difference between the compose stack and three local
# binaries. Every entry is a name or a path, never a threshold or an interval.
# Adding a behavioural substitution here would be caught by the drift test only
# if it changes a line that carries no address, so the rule is simpler than the
# test: if it is not a hostname, a port or a filesystem path, it does not belong
# in this list.
ADDRESSES: dict[str, str] = {
    "host.docker.internal": "127.0.0.1",
    "alertmanager:9093": "127.0.0.1:9093",
    "prometheus:9090": "127.0.0.1:9090",
    "/etc/prometheus/rules/*.yml": None,   # filled in at render time: absolute
    "/var/lib/grafana/dashboards": None,   # filled in at render time: absolute
}

# Files rendered from monitoring/ into the local tree, as source -> destination
# relative to each root.
RENDERED = [
    "prometheus.yml",
    "alertmanager.yml",
    "grafana/provisioning/datasources/prometheus.yml",
    "grafana/provisioning/dashboards/dashboards.yml",
]

BANNER = (
    "# GENERATED by scripts/monitoring_local.py from {src}. Do not edit.\n"
    "# Behaviour lives in that file; this copy differs only in addresses.\n"
    "# Regenerate with: make monitoring-local\n"
)


def substitutions(dashboards_dir: Path, rules_dir: Path | None = None) -> dict[str, str]:
    """The address map, with the two path entries resolved.

    Both default to this repository. They are overridable because the process
    reading the config does not always see the repository at the path this
    script sees it at -- a mount, a share, a container -- and a rendered config
    full of paths that are correct only on the rendering machine is a config
    that starts and then finds nothing.
    """
    subs = {k: v for k, v in ADDRESSES.items() if v is not None}
    rules = rules_dir or (MONITORING / "rules")
    subs["/etc/prometheus/rules/*.yml"] = _posix(Path(rules) / "*.yml")
    subs["/var/lib/grafana/dashboards"] = _posix(dashboards_dir)
    return subs


def _posix(p: Path) -> str:
    """Forward slashes everywhere. Prometheus and Grafana both accept them on
    Windows, and a backslash in a YAML double-quoted scalar is an escape."""
    return str(p).replace("\\", "/")


def render(text: str, subs: dict[str, str]) -> str:
    # Longest first, so "alertmanager:9093" is replaced before a shorter key
    # could match inside it.
    for old in sorted(subs, key=len, reverse=True):
        text = text.replace(old, subs[old])
    return text


def render_all(out: Path, dashboards_dir: Path, rules_dir: Path | None = None,
               *, banner: bool = True, dests: dict[str, Path] | None = None) -> list[Path]:
    """Render every file in RENDERED.

    `dests` overrides where an individual file lands, keyed by its path in
    RENDERED. Binaries installed by hand rarely read from one tidy tree -- this
    repository's own local stack keeps Prometheus's config beside the binary and
    Grafana's provisioning three directories down -- and rendering straight into
    those places is what stops somebody copying the output by hand afterwards,
    which is how the second copy appears again.
    """
    subs = substitutions(dashboards_dir, rules_dir)
    written = []
    for rel in RENDERED:
        src = MONITORING / rel
        dst = (dests or {}).get(rel, out / rel)
        dst.parent.mkdir(parents=True, exist_ok=True)
        body = render(src.read_text(encoding="utf-8"), subs)
        head = BANNER.format(src=f"monitoring/{rel}") if banner else ""
        dst.write_text(head + body, encoding="utf-8")
        written.append(dst)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=REPO / ".local" / "monitoring",
                    help="where to write the rendered config")
    ap.add_argument("--dashboards-dir", type=Path, default=None,
                    help="folder Grafana provisions dashboards from; the repo's "
                         "monitoring/grafana/dashboards by default, so there is "
                         "one dashboard file rather than a copy")
    ap.add_argument("--copy-dashboards-to", type=Path, default=None,
                    help="also copy the dashboards there, for a Grafana whose "
                         "provider path cannot be changed without a restart")
    ap.add_argument("--rules-dir", type=Path, default=None,
                    help="alert rules directory as the running Prometheus sees "
                         "it; this repo's monitoring/rules by default")
    ap.add_argument("--prometheus-config", type=Path, default=None,
                    help="write prometheus.yml here instead of under --out")
    ap.add_argument("--alertmanager-config", type=Path, default=None,
                    help="write alertmanager.yml here instead of under --out")
    ap.add_argument("--grafana-provisioning", type=Path, default=None,
                    help="write Grafana's provisioning tree here instead of "
                         "under --out (the conf/provisioning of a real install)")
    args = ap.parse_args(argv)

    dash = args.dashboards_dir or (MONITORING / "grafana" / "dashboards")

    dests: dict[str, Path] = {}
    if args.prometheus_config:
        dests["prometheus.yml"] = args.prometheus_config
    if args.alertmanager_config:
        dests["alertmanager.yml"] = args.alertmanager_config
    if args.grafana_provisioning:
        for rel in RENDERED:
            if rel.startswith("grafana/provisioning/"):
                tail = rel[len("grafana/provisioning/"):]
                dests[rel] = args.grafana_provisioning / tail

    written = render_all(args.out, dash, args.rules_dir, dests=dests)
    for p in written:
        print(f"wrote {p}")

    if args.copy_dashboards_to:
        args.copy_dashboards_to.mkdir(parents=True, exist_ok=True)
        for j in sorted((MONITORING / "grafana" / "dashboards").glob("*.json")):
            shutil.copy2(j, args.copy_dashboards_to / j.name)
            print(f"copied {j.name} -> {args.copy_dashboards_to}")

    print()
    print("Start the three binaries against it, from the repository root:")
    print(f"  prometheus   --config.file={_posix(args.out / 'prometheus.yml')} "
          f"--web.enable-lifecycle")
    print(f"  alertmanager --config.file={_posix(args.out / 'alertmanager.yml')}")
    print(f"  grafana server --homepath <grafana>  "
          f"# provisioning: {_posix(args.out / 'grafana' / 'provisioning')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
